### ISSUE TITLE
Change owner to MaayanLab 

### ISSUE THREAD

**Issue by zero323** [nasb-course/nasb-microtask-viewer-shiny#18]
@wangz10 Could you take care of this? I don't think there is a point in keeping this as a standalone organization any longer. I merged all related code into a single repo and cleaned other repositories. 

Thanks in advance.

**Comment by wangz10** [comment]
Transfered. @zero323 thanks for your contribution to this app. We also have another repo [Maayanlab/PAEA](https://github.com/MaayanLab/PAEA) hosting the scripts for the app running on [http://amp.pharm.mssm.edu/PAEA/](http://amp.pharm.mssm.edu/PAEA/)

**Comment by zero323** [comment]
Thanks @wangz10 

I doubt there is any point in trying to merge these. It looks like we've diverged quite a lot.

**Comment by wangz10** [comment]
@zero323 I agree. We can have both repos stay as they are.
