### ISSUE TITLE
Characteristic Direction analysis should return lower number of the significant genes.

### ISSUE THREAD

**Issue by zero323** [nasb-course/nasb-microtask-viewer-shiny#4]
> I think the Characteristic Direction analysis should return less significant genes. The example returns over 700 genes that are significant out of 900 and this is too many. The number of significant genes should typically be around 5% of all genes... This is not your fault but an issue with the way GeoDE is implemented.

Source: Avi Ma'ayan ,  https://class.coursera.org/netsysbio-002/forum/thread?thread_id=124#post-613

**Comment by MaayanLab** [comment]
You can make it default to 250 up and 250 down genes... but a better cutoff is needed in general
